StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6920E020A5AAD65D}" {
   Id "SAS-Freezetime_Description"
   Target_en_us "Preparation and organization time. Stay at the MAIN BASE."
   Target_en_us_edited ""
   Target_fr_fr "Temps de préparation et d'organisation. Restez à la BASE PRINCIPALE."
   Target_it_it "Tempo di preparazione e organizzazione. Rimani alla BASE PRINCIPALE."
   Target_de_de "Vorbereitungs- und Organisationszeit. Bleibe in der HAUPTBASIS."
   Target_es_es "Tiempo de preparación y organización. Quédate en la BASE PRINCIPAL."
   Target_cs_cz "Čas na přípravu a organizaci. Zůstaňte na HLAVNÍ ZÁKLADNĚ."
   Target_pl_pl "Czas na przygotowanie i organizację. Pozostań w BAZIE GŁÓWNEJ."
   Target_ru_ru "Время подготовки и организации. Оставайтесь на ГЛАВНОЙ БАЗЕ."
   Target_ja_jp "準備と組織化の時間です。メイン基地に留まってください。"
   Target_ko_kr "준비 및 조직 시간입니다. 메인 베이스에 머무르십시오."
   Target_pt_br "Momento de preparação e organização dos times. Mantenha-se na MAIN BASE."
   Target_zh_cn "准备和组织时间。留在主基地。"
   Target_uk_ua "Час для підготовки та організації. Залишайтеся на ГОЛОВНІЙ БАЗЕ."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1770397189
   Author "Binho"
   LastChanged "Binho"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{6920E020A5AAD65E}" {
   Id "SAS-Freezetime_EndDescription"
   Target_en_us "All released. Proceed to the objective."
   Target_en_us_edited ""
   Target_fr_fr "Tout le monde est libéré. Procédez à l'objectif."
   Target_it_it "Tutti liberi. Procedete verso l'obiettivo."
   Target_de_de "Alle freigegeben. Geht zum Einsatzziel."
   Target_es_es "Todos liberados. Procedan al objetivo."
   Target_cs_cz "Všichni propuštěni. Postupujte k cíli."
   Target_pl_pl "Wszyscy wolni. Przejdźcie do celu."
   Target_ru_ru "Все свободны. Двигайтесь к цели."
   Target_ja_jp "全員解除されました。目標に向かって進んでください。"
   Target_ko_kr "모두 해제되었습니다. 목표로 진행하십시오."
   Target_pt_br "Todos liberados. Sigam para o objetivo."
   Target_zh_cn "全部释放。前往目标。"
   Target_uk_ua "Всі вільні. Рухайтеся до цілі."
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1770397189
   Author "Binho"
   LastChanged "Binho"
   ImageLink ""
   Hidden 0
  }
  CustomStringTableItem "{6920E020A5AAD65C}" {
   Id "SAS-Freezetime_Title"
   Target_en_us "FREEZE TIME"
   Target_en_us_edited ""
   Target_fr_fr "FREEZE TIME"
   Target_it_it "FREEZE TIME"
   Target_de_de "FREEZE TIME"
   Target_es_es "FREEZE TIME"
   Target_cs_cz "FREEZE TIME"
   Target_pl_pl "FREEZE TIME"
   Target_ru_ru "FREEZE TIME"
   Target_ja_jp "FREEZE TIME"
   Target_ko_kr "FREEZE TIME"
   Target_pt_br "FREEZE TIME"
   Target_zh_cn "FREEZE TIME"
   Target_uk_ua "FREEZE TIME"
   Comment ""
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status DEVELOPMENT_PENDING
   NonTranslatable 0
   MaxLength 0
   Modified 1770397189
   Author "Binho"
   LastChanged "Binho"
   ImageLink ""
   Hidden 0
  }
 }
}